#!/usr/bin/env bash
# Lists/adds/removes/enables/disables bar-widget plugins - the Quickshell-side
# analog of Omarchy's `omarchy plugin list/add/remove/enable/disable`.
# Plugins come from three places (see quickshell/plugin-registry.json,
# generated by desktop/home.nix's quickshellPlugins activation step):
#   - builtin:  quickshell/plugins/user.*/, hand-edited in this checkout
#   - external: declared in ../plugins/default.nix (id -> pkgs.fetchFromGitHub
#     or any other fetchgit/fetchTarball-compatible source), fetched
#     reproducibly by Nix and symlinked into quickshell/plugins/<id> on
#     `nixos-rebuild switch` - the *declarative* route.
#   - manual:   `plugin.sh add <git-url>` below, a real `git clone` into
#     quickshell/plugins/<id> - the *non-declarative* route, exactly like
#     Omarchy's own `omarchy plugin add <url> --enable`. Nothing about this
#     is Nix-managed: the cloned files stay put across rebuilds (the
#     activation step only ever removes *symlinks* under plugins/, never
#     real directories), but plugin-registry.json is fully regenerated by
#     that same activation step from builtin manifests + ../plugins/
#     default.nix - so a manual plugin's registry row (used to validate
#     `enable`/show up in `list`) will disappear on the next
#     `nixos-rebuild switch` unless you also add it to ../plugins/
#     default.nix. Its *enabled* state in plugin-layout.json is untouched
#     either way - Nix never writes that file, only this script does.
#
# Enabling/disabling only edits plugin-layout.json (which ids are on the bar
# and where) - it never touches plugin-registry.json (which ids *exist*),
# so this script works the same for all three origins without needing to
# know which one it's touching.
#
# Compatibility note for a real Omarchy-catalog plugin (omarchyplugins.com):
# its manifest.json is understood either way (see PluginRow.qml's manifest
# normalization), but its QML may import `qs.Commons`/`qs.Ui` - Omarchy's
# own Style/Color/BarIconButton/etc. design-system modules, which this
# shell does not provide. Such a plugin will fetch/clone and enable fine
# but its widget will fail to load until those modules are ported here.
set -euo pipefail

config_dir="$HOME/.config/quickshell"
plugins_dir="$config_dir/plugins"
registry_file="$config_dir/plugin-registry.json"
layout_file="$config_dir/plugin-layout.json"

usage() {
  echo "usage: plugin.sh list" >&2
  echo "       plugin.sh add <git-url> [--enable]" >&2
  echo "       plugin.sh remove <id>" >&2
  echo "       plugin.sh enable <id> [left|center|right]" >&2
  echo "       plugin.sh disable <id>" >&2
  exit 1
}

# Multi-file plugins (e.g. a widget that instantiates sibling files like
# UsageGrid.qml/BoundedReader.qml as bare types) rely on Quickshell's
# implicit per-directory type synthesis - which does NOT reliably apply to
# files loaded under Quickshell's own `qs:` scheme (used for everything
# under ~/.config/quickshell/, including plugin directories), even though
# it works for single-file plugins. Symptom: "X is not a type" in
# `quickshell log`, and the widget silently never renders. Generating an
# explicit qmldir (no `module` line, so it works for same-directory access
# without an import, exactly like the implicit case was supposed to)
# sidesteps the limitation. Skipped if the plugin ships its own qmldir -
# never override one a plugin author wrote on purpose.
generate_plugin_qmldir() {
  local dir="$1"
  [ -f "$dir/qmldir" ] && return
  local f base
  {
    for f in "$dir"/*.qml; do
      [ -e "$f" ] || continue
      base=$(basename "$f" .qml)
      echo "$base 1.0 $(basename "$f")"
    done
  } > "$dir/qmldir"
}

register_manual_plugin() {
  local id="$1" name="$2"
  local tmp
  tmp=$(mktemp)
  jq --arg id "$id" --arg name "$name" '
    (map(select(.id != $id))) + [{id: $id, name: $name, kind: "bar-widget", origin: "manual"}]
  ' "$registry_file" > "$tmp"
  mv "$tmp" "$registry_file"
}

case "${1:-}" in
  list)
    jq -r '
      .[] | "\(.id)\t\(.name)\t\(.origin)"
    ' "$registry_file" | while IFS=$'\t' read -r id name origin; do
      section=$(jq -r --arg id "$id" '
        to_entries[] | select(.value | index($id)) | .key
      ' "$layout_file" | head -n1)
      if [ -n "$section" ]; then
        printf '%-24s %-20s %-10s enabled (%s)\n' "$id" "$name" "$origin" "$section"
      else
        printf '%-24s %-20s %-10s disabled\n' "$id" "$name" "$origin"
      fi
    done
    ;;
  add)
    url="${2:-}"
    [ -n "$url" ] || usage
    enable=false
    for arg in "${@:3}"; do
      [ "$arg" = "--enable" ] && enable=true
    done

    clone_tmp=$(mktemp -d)
    trap 'rm -rf "$clone_tmp"' EXIT
    git clone --quiet --depth 1 "$url" "$clone_tmp"

    manifest="$clone_tmp/manifest.json"
    [ -f "$manifest" ] || {
      echo "no manifest.json at the root of $url" >&2
      exit 1
    }
    id=$(jq -r '.id // empty' "$manifest")
    name=$(jq -r '.name // empty' "$manifest")
    [ -n "$id" ] || {
      echo "manifest.json has no \"id\"" >&2
      exit 1
    }

    target="$plugins_dir/$id"
    rm -rf "$target"
    mkdir -p "$plugins_dir"
    mv "$clone_tmp" "$target"
    trap - EXIT

    generate_plugin_qmldir "$target"
    register_manual_plugin "$id" "${name:-$id}"
    echo "added $id (from $url) into $target"

    if $enable; then
      # Our own manifests carry `section`; real Omarchy manifests carry
      # `barWidget.defaultSection` (see PluginRow.qml's manifest
      # normalization) - honor whichever is present, default to right.
      default_section=$(jq -r '.section // .barWidget.defaultSection // "right"' "$target/manifest.json")
      "$0" enable "$id" "$default_section"
    fi
    ;;
  remove)
    id="${2:-}"
    [ -n "$id" ] || usage
    rm -rf "${plugins_dir:?}/$id"
    tmp=$(mktemp)
    jq --arg id "$id" 'map(select(.id != $id))' "$registry_file" > "$tmp"
    mv "$tmp" "$registry_file"
    tmp=$(mktemp)
    jq --arg id "$id" 'with_entries(.value |= map(select(. != $id)))' "$layout_file" > "$tmp"
    mv "$tmp" "$layout_file"
    echo "removed $id"
    ;;
  enable)
    id="${2:-}"
    section="${3:-right}"
    [ -n "$id" ] || usage
    case "$section" in
      left | center | right) ;;
      *)
        echo "section must be left, center, or right" >&2
        exit 1
        ;;
    esac
    if ! jq -e --arg id "$id" '.[] | select(.id == $id)' "$registry_file" >/dev/null; then
      echo "no such plugin: $id (see 'plugin.sh list')" >&2
      exit 1
    fi
    tmp=$(mktemp)
    jq --arg id "$id" --arg section "$section" '
      # Drop the id from every section first, so enabling it somewhere new
      # also moves it rather than leaving a duplicate behind.
      with_entries(.value |= map(select(. != $id)))
      | .[$section] += [$id]
    ' "$layout_file" > "$tmp"
    mv "$tmp" "$layout_file"
    echo "enabled $id in $section"
    ;;
  disable)
    id="${2:-}"
    [ -n "$id" ] || usage
    tmp=$(mktemp)
    jq --arg id "$id" '
      with_entries(.value |= map(select(. != $id)))
    ' "$layout_file" > "$tmp"
    mv "$tmp" "$layout_file"
    echo "disabled $id"
    ;;
  *)
    usage
    ;;
esac
