// Every plugin the shell knows about (builtin under quickshell/plugins/user.*
// and third-party ones declared in ../plugins/default.nix), independent of
// whether it's currently on the bar - that's plugin-layout.json's job (see
// PluginRow.qml), edited via quickshell/scripts/plugin.sh. Regenerated by
// desktop/home.nix's quickshellPlugins activation step into
// ~/.config/quickshell/plugin-registry.json on every `nixos-rebuild
// switch`; this singleton just watches that file the same way Colors.qml
// watches theme.json, so a settings UI listing "available plugins" doesn't
// need its own file-reading boilerplate.
pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

Scope {
    id: root

    // Array of { id, name, kind, origin, entryPoint?, section?, tooltip? }
    // - entryPoint/section/tooltip are only present for builtin entries
    // (read from the real manifest.json at eval time); external entries
    // carry just id/name/kind/origin here since PluginRow.qml reads the
    // rest from the plugin's own manifest.json lazily, once enabled.
    property var plugins: []

    function isEnabled(layout, id) {
        if (!layout)
            return false;
        for (const section of ["left", "center", "right"]) {
            if ((layout[section] || []).indexOf(id) !== -1)
                return true;
        }
        return false;
    }

    FileView {
        id: registryFile
        path: `${Quickshell.env("HOME")}/.config/quickshell/plugin-registry.json`
        watchChanges: true
        onFileChanged: reload()
        onLoaded: {
            try {
                root.plugins = JSON.parse(text());
            } catch (e) {
                console.warn("PluginRegistry: failed to parse plugin-registry.json: " + e);
            }
        }
    }
}
