font_family      JetBrainsMono Nerd Font
font_size        10.0

cursor_shape            block
cursor_blink_interval   0
confirm_os_window_close 0
window_padding_width    0
wheel_scroll_multiplier 0.95

background            #1e1512
foreground             #e0c2a8
cursor                 #ffb37a
selection_background   #33241c
selection_foreground   #ffe1c2

color0  #1e1512
color1  #f7768e
color2  #b9ca6a
color3  #e0af68
color4  #e8935c
color5  #dba463
color6  #ffb37a
color7  #e0c2a8
color8  #4a3728
color9  #ff9e8e
color10 #d9c98a
color11 #ffcf8c
color12 #ffab73
color13 #f0b98a
color14 #ffd1a3
color15 #f5e3d0
